version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup
    networks:
      - mintcat
    hostname: watchtower.local

  xui:
    image: enwaiax/x-ui:alpha-zh
    container_name: xui
    volumes:
      - xui_db:/etc/x-ui/
      - xui_cert:/root/cert/
    restart: unless-stopped
    networks:
      - mintcat
    hostname: xui.local

  nginx:
    image: jc21/nginx-proxy-manager
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx_data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - mintcat
    hostname: nginx.local

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=vaultwarden
      - MYSQL_USER=vaultwarden_user
      - MYSQL_PASSWORD=vw_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mintcat
    hostname: mysql.local

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - vaultwarden_data:/data
    environment:
      - DATABASE_URL=mysql://vaultwarden_user:vw_password@mysql.local/vaultwarden
      - PUID=0
      - PGID=0
    depends_on:
      - mysql
    networks:
      - mintcat
    hostname: vaultwarden.local

  portainer_agent:
    image: portainer/agent:2.21.5
    container_name: portainer_agent
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    networks:
      - mintcat
    hostname: portainer-agent.local

  portainer_ce:
    image: portainer/portainer-ce:lts
    container_name: portainer_ce
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - mintcat
    hostname: portainer-ce.local

  tor:
    image: dockurr/tor
    container_name: tor
    restart: always
    volumes:
      - tor_config:/etc/tor
      - tor_data:/var/lib/tor
    networks:
      - mintcat
    stop_grace_period: 1m
    hostname: tor.local

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql.local   # 使用本地域名连接 MySQL
      - PMA_PORT=3306
    ports:
      - "8082:80"
    depends_on:
      - mysql
    networks:
      - mintcat
    hostname: phpmyadmin.local

networks:
  mintcat:
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"  # 修改为不冲突的子网

volumes:
  xui_db:
  xui_cert:
  nginx_data:
  letsencrypt:
  vaultwarden_data:
  portainer_data:
  tor_config:
  tor_data:
  mysql_data:
