version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_INITDB_SKIP_TZINFO: "true"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      mintcat:
        ipv4_address: 172.21.10.6
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - vaultwarden_data:/data
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=true
      - ADMIN_TOKEN=${BITWARDEN_ADMIN_TOKEN:-changeme_admin_token}
      - DATABASE_URL=mysql://<数据库用户名>:<数据库用户密码>@<数据库公网地址>:<数据库端口>/<数据库名称>
    networks:
      mintcat:
        ipv4_address: 172.21.10.5
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx_data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      mintcat:
        ipv4_address: 172.21.10.7

  portainer_ce:
    image: portainer/portainer-ce:2.21.5
    container_name: portainer_ce
    restart: unless-stopped
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      mintcat:
        ipv4_address: 172.21.10.3

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --schedule "0 3 * * *"
    restart: unless-stopped
    networks:
      mintcat:
        ipv4_address: 172.21.10.9

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1G
    networks:
      mintcat:
        ipv4_address: 172.21.10.11

  tor:
    image: dockurr/tor:latest
    container_name: tor
    restart: always
    volumes:
      - tor_config:/etc/tor
      - tor_data:/var/lib/tor
    networks:
      mintcat:
        ipv4_address: 172.21.10.2
    stop_grace_period: 1m

  xui:
    image: enwaiax/x-ui:alpha-zh
    container_name: xui
    volumes:
      - xui_db:/etc/x-ui
      - xui_cert:/root/cert
    restart: unless-stopped
    networks:
      mintcat:
        ipv4_address: 172.21.10.8

  alist:
    image: xhofe/alist:latest
    container_name: alist
    restart: always
    volumes:
      - alist_data:/opt/alist/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=alist
      - DB_PASSWORD=alist_password
      - DB_NAME=alist
    ports:
      - "5244:5244"
    networks:
      mintcat:
        ipv4_address: 172.21.10.10
    depends_on:
      mysql:
        condition: service_healthy

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    ports:
      - "3000:3000"
    networks:
      mintcat:
        ipv4_address: 172.21.10.12

  # freqtrade服务配置
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade_bot
    restart: unless-stopped
    volumes:
      - freqtrade_user_data:/freqtrade/user_data            # 运行数据（数据库、日志等）
      - freqtrade_config:/freqtrade/config.json:ro          # 配置文件（命名卷，建议初始化）
      - freqtrade_strategies:/freqtrade/strategies:ro       # 策略代码目录（命名卷，建议初始化）
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      trade
      --config /freqtrade/config.json
      --strategy DualTrendGridStrategy
      --datadir /freqtrade/user_data/data
      --rpc  # 启用 RPC 接口
    networks:
      mintcat:
        ipv4_address: 172.21.10.4
        
  frequi:
    image: freqtradeorg/frequi
    container_name: frequi
    restart: unless-stopped
    depends_on:
      - freqtrade
    ports:
      - "8088:8080"  # 外部访问端口 → 内部服务端口
    environment:
      - FREQTRADE_URI=http://172.21.10.4:8080  # 指向 freqtrade RPC API 地址
      - USERNAME=admin
      - PASSWORD=changeme123  # 请修改为强密码
    networks:
      mintcat:
        ipv4_address: 172.21.10.13
        
volumes:
  mysql_data:
    driver: local
  vaultwarden_data:
    driver: local
  nginx_data:
    driver: local
  letsencrypt:
    driver: local
  portainer_data:
    driver: local
  tor_config:
    driver: local
  tor_data:
    driver: local
  xui_db:
    driver: local
  xui_cert:
    driver: local
  alist_data:
    driver: local
  adguard_work:
    driver: local
  adguard_conf:
    driver: local
  freqtrade_user_data:
    driver: local
  freqtrade_config:
    driver: local
  freqtrade_strategies:
    driver: local
networks:
  mintcat:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.10.0/24
